# Generated by Django 5.1.2 on 2024-10-23 08:25

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('parcourinf_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='statuts',
            field=models.CharField(choices=[('1', 'En attente'), ('2', 'Acceptée'), ('3', 'Refusée')], default='1', max_length=100),
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('demande', models.ManyToManyField(to='parcourinf_project.demande')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
