# Generated by Django 5.1.2 on 2024-10-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcourinf_project', '0002_demande_statuts_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='nom',
            field=models.CharField(default='nouvelle ecole', max_length=255),
            preserve_default=False,
        ),
    ]
