# Generated by Django 5.1.2 on 2024-10-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcourinf_project', '0003_ecole_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='img',
            field=models.CharField(default='https://st.depositphotos.com/1001911/4773/v/450/depositphotos_47738095-stock-illustration-begging-emoticon.jpg', max_length=255),
        ),
    ]
